name: yts_mobile
description: A simple mobile app for accessing movies of [YTS website](https://yts.mx/).

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  clock: ^1.1.1
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  equatable: ^2.0.5
  file: ^6.1.4
  firebase_core: ^2.4.0
  flex_color_scheme: ^6.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.2.0
  go_router: ^6.0.0
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.7.0
  lottie: ^2.1.0
  mocktail_image_network: ^0.3.1
  shimmer: ^2.0.0
  stack_trace: ^1.10.0
  url_launcher: ^6.1.7

dev_dependencies:
  build_runner: ^2.3.0
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  hive_test: ^1.0.1
  http_mock_adapter: ^0.3.3
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  test_coverage_badge: ^0.2.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/svg/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
