version: 2.1

orbs:
  flutter: circleci/flutter@1.1.0

executors:
  android:
    docker:
      - image: 'cimg/android:2022.06'

commands:
  install-flutter:
    steps:
      - checkout
      - run:
          name: Set Flutter vesion
          command: echo 'export FLUTTER_VERSION="3.3.9"' >> $BASH_ENV
      - flutter/install_sdk_and_pub:
          flutter_version: ${FLUTTER_VERSION}
      - run: flutter pub run build_runner build --delete-conflicting-outputs
  dart_analyze:
    steps:
      - run:
          name: Check analyze
          command: |
            flutter analyze || exit
  build-android:
    description: Builds APK for Android
    steps:
      - run:
          command: flutter build apk
          name: Build APK
  format:
    description: Run checks if Flutter code is formatted
    steps:
      - run:
          command: >-
            flutter format --set-exit-if-changed . || { echo 'Format check
            failed'; exit 1; }
          name: Analyze
  test:
    description: Runs the tests of your Flutter app
    steps:
      - run:
          command: flutter test
          name: Test

jobs:
  setup-and-format:
    executor:
      name: android
    steps:
      - checkout
      - install-flutter
      - format
      - dart_analyze
      - run: flutter test --no-sound-null-safety
  build-android:
    executor: android
    steps:
      - checkout
      - install-flutter
      - build-android
  tests:
    executor: android
    steps:
      - checkout
      - install-flutter
      - format
      - dart_analyze
      - test

workflows:
  main:
    jobs:
      - setup-and-format
      - tests
      - build-android:
          requires:
            - setup-and-format
            - tests